### ISSUE TITLE
Flicker at first character of the line in Windows

### ISSUE THREAD

**Issue by jonathandturner** [kkawakam/rustyline#256]
Rustyline currently seems to flicker at the first character when typing/backspacing, but this seems to only affect Windows - I haven't seen it on Linux.

I tried to record an animated gif so you can see it:

![rustyline_flicker](https://user-images.githubusercontent.com/547158/62581883-ae7ad400-b8fe-11e9-8e47-af13a227e188.gif)

In practice, it flickers more than you can see in the gif, but this should at least show where it's flickering.

**Comment by gwenn** [comment]
Sorry, I don't have access to a Windows 10 console.
I will try to reproduce with `ConEmu` on Windows 7.
If you can do the same test with `linefeed` or `replxx`, tell me if they flicker or not.

**Comment by jonathandturner** [comment]
I don't see the same flicker using `linefeed` (though I think the performance of rustyline is a bit better on Windows, from what I could tell)

**Comment by gwenn** [comment]
Ok, I can reproduce this issue on Windows 7.
It happens when we do a full refresh/redraw of the line (because there is an hint/suggestion or when you press backspace).
There is a WIP [here](https://github.com/gwenn/rustyline/tree/redraw) to optimise refresh.
I guess screen flickers because the cursor is first [moved](https://github.com/kkawakam/rustyline/blob/master/src/tty/windows.rs#L325) at column zero.
I will try to avoid moving the cursor.

**Comment by gwenn** [comment]
https://github.com/AmokHuginnsson/replxx/commit/40774d131eba1aced11447d7bb21070f1678f243
=> Hide / Show cursor
=> Clear screen with an ANSI escape sequence when supported

**Comment by gwenn** [comment]
Could you please give PR #370 a try ?

**Comment by gwenn** [comment]
Should be fixed in 6.1.2
