### ISSUE TITLE
bind_sequence requires two presses to trigger

### ISSUE THREAD

**Issue by madprops** [kkawakam/rustyline#264]
`editor.bind_sequence(KeyPress::Esc, Cmd::Interrupt);`

I expect it to stop the input (Currently that works with ctrl+c). But it requires Esc to be pressed twice in order to work. Seems it's only an issue with Esc. Changing it to Home for instance works on a single press. This is on Terminator -> Linux

I don't know if this is intended.

**Comment by gwenn** [comment]
It's because the Esc key is used to trigger Meta- sequence.
For example, Esc + b gives Meta-b (move cursor to previous word).
But you can try to use [keyseq_timeout](https://docs.rs/rustyline/5.0.1/rustyline/config/struct.Builder.html#method.keyseq_timeout).

https://github.com/kkawakam/rustyline/blob/master/examples/example.rs#L73
```rust
    let config = Config::builder()
        .history_ignore_space(true)
        .completion_type(CompletionType::List)
        .edit_mode(EditMode::Emacs)
        .keyseq_timeout(250) // wait 250ms to make the distinction between a single escape and a sequence 
        .output_stream(OutputStreamType::Stdout)
        .build();
```
