### ISSUE TITLE
EOF error on latest release

### ISSUE THREAD

**Issue by kkawakam** [kkawakam/rustyline#27]
~~Going to yank 0.2.2 after a fix is in place.~~

**Comment by saghm** [comment]
Weirdly, it seems to work fine if you run the binary in `target` manually

**Comment by saghm** [comment]
Okay, from what I can tell, when the binary is invoked with `cargo run`, then `libc::isatty` seems to return 0 rather than one; then, in `readline_direct`, `io::stdin().read_line()` seems to return 0. I'm not certain if it's an issue with libc or what, but it actually doesn't seem to stem from the updates in 0.2.2.

**Comment by saghm** [comment]
For reference, I opened an issue in the `libc` crate to find out whether this is expected behavior or not.

https://github.com/rust-lang/libc/issues/239

**Comment by saghm** [comment]
It appears to have been fixed in 2016-03-29. It seems to have been an issue in `rustc`, which was fixed in https://github.com/rust-lang/rust/pull/32257

**Comment by kkawakam** [comment]
Fixed in latest rust-nightly (b678600ac 2016-03-29)
