### ISSUE TITLE
`ValidationResult::Incomplete` and `ValidationResult::Invalid` have same effect

### ISSUE THREAD

**Issue by zachmatson** [kkawakam/rustyline#404]
I was trying to implement the `Validator` trait to prevent a line from being accepted if it was invalid by returning the `Invalid` variant of `ValidationResult`, but with either this or `Incomplete` multi-line input mode is entered. Shouldn't one of these be for multi-line input and the other just hold up the current line from being passed on?

**Comment by gwenn** [comment]
Currently, you can't:
* `Incomplete` is used when  something is missing.
* `Invalid` is used when current input is invalid and you can use either syntax highlighting or a message / suggestion as an hint.
Both mean "reject input".
If you want to accept an invalid input, you must use `Valid`.
Because `Valid` means "accept input".

**Comment by zachmatson** [comment]
This seems unclear from an API standpoint of each of those had the same effect. I suppose `Incomplete` sounds like a newline should be inserted so the user can keep typing, while `Invalid` sounds like the input is flawed and contains some error. But I guess that's more an opinion than a bug anyways.
