### ISSUE TITLE
Windows still panics in some cases

### ISSUE THREAD

**Issue by jonathandturner** [kkawakam/rustyline#433]
Hi all,

Thanks for the fixes to, I think we managed to fix some of our Windows instability with this PR: https://github.com/kkawakam/rustyline/issues/359

Unfortunately, users are still reporting very similar issues. I haven't been able to reproduce it, yet, but I wanted to file an issue in case you are able to reproduce: https://github.com/nushell/nushell/issues/2440

Happy to help wherever we can.

**Comment by gwenn** [comment]
A backtrace would be helpful.

**Comment by jonathandturner** [comment]
@gwenn - I'll ask and see if I can get a backtrace

**Comment by Lucretiel** [comment]
I've tracked down the specific issue to here: https://github.com/kkawakam/rustyline/blob/32f87be475234c7ffbdf2ecb603411423c37eeaf/src/tty/windows.rs#L514-L516

The problem is that, when running in a terminal that *isn't* cmd.exe (like Windows Terminal), `set_console_cursor_position` returns an error code 87, which matches `ErrorKind::InvalidInput`. It appears that errno 87 is *always* `InvalidInput` (per https://github.com/rust-lang/rust/blob/master/library/std/src/sys/windows/mod.rs#L64), so I think this line needs to be changed. I'll submit a PR making the change.

**Comment by gwenn** [comment]
v6.3.0 released
