### ISSUE TITLE
how to setcompleter with AutoSuggestCompleter and Editor?

### ISSUE THREAD

**Issue by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [kkawakam/rustyline#719]
I currently have something like>
```
let completer = AutoSuggestCompleter { options: args };
    let mut rl: Editor<()> = Editor::with_config(config);
    rl.bind_sequence(KeyEvent(KeyCode::Tab, Modifiers::NONE), rustyline::Cmd::Complete);
```

___________
I looked around the Editor struct but i dont see set_completer() or similar function that accepts completer object.
I am new to rust so I depend on chatgpt a bit,and it tells me to use rl.set_completer(Some(Box::new(completer)));
But of course the api changed.Does anyone know what is the equivalent function for that?

**Comment by gwenn** [comment]
We hope that one day `Completer` / `Hinter` / `Validator` / `Highlighter` will share / use not a string (`&str`) but an AST / tokens so that user input is parsed only once instead of being parsed by each one of these traits impls.
So they are provided by an `Helper` trait.
 If you want to provide only an `Hinter`, you have to derive or implement the other traits.
See https://github.com/kkawakam/rustyline/blob/master/examples/example.rs#L11-L21

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
sorry i wanted to try your example code https://github.com/kkawakam/rustyline/blob/master/examples/example.rs but it seems to not compile?
error: cannot find derive macro `Helper` in this scope
  --> src\main.rs:12:10
   |
12 | #[derive(Helper, Completer, Hinter, Validator)]

**Comment by gwenn** [comment]
see https://github.com/kkawakam/rustyline/blob/934a7dc11f895ec5002da605d51c666307d279d6/Cargo.toml#L79-L81

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
huge thanks,it worked.still kinda confused but I think will put some time reading the example and play with it.will close this for now.
